#!/bin/bash
# Generates secrets/bw.env, technitium/terraform/local/{terraform,staging}.tfvars,
# and technitium/cloud-init/local/technitium-user{,-ns2}.yaml from one
# consolidated source file, secrets/deployment.env (gitignored, see
# secrets/deployment.env.sample for the template). Edit that ONE file, then
# re-run this script (`make generate-config`) instead of hand-editing five
# separate files.
#
# Does NOT touch technitium/ansible/configure-technitium-apps.yaml's
# optional DNS Apps -- those are still enabled/disabled by hand.
#
# Never echoes a secret value -- only which files were written.
set -euo pipefail

cd "$(dirname "$0")/.."

DEPLOYMENT_ENV="secrets/deployment.env"

if [ ! -f "$DEPLOYMENT_ENV" ]; then
    echo "Missing $DEPLOYMENT_ENV" >&2
    echo "Copy secrets/deployment.env.sample to $DEPLOYMENT_ENV and fill in your real values." >&2
    exit 1
fi

set -a
# shellcheck source=/dev/null
source "$DEPLOYMENT_ENV"
set +a

mkdir -p technitium/terraform/local technitium/cloud-init/local

###############################################################################
# secrets/bw.env
###############################################################################
{
    echo "BW_TOKEN=\"${BW_TOKEN}\""
    echo "BW_ORGID=\"${BW_ORGID}\""
    echo "BW_PROJECTID=\"${BW_PROJECTID}\""
    echo "TECHNITIUM_ADMIN_PASSWORD=\"${TECHNITIUM_ADMIN_PASSWORD}\""
    echo "ACME_EMAIL=\"${ACME_EMAIL}\""
    echo "CLOUDFLARE_API_TOKEN=\"${CLOUDFLARE_API_TOKEN}\""
    echo "OPNSENSE_API_CONFIG={\"host\":\"${OPNSENSE_HOST}\",\"apiKey\":\"${OPNSENSE_API_KEY}\",\"apiSecret\":\"${OPNSENSE_API_SECRET}\"}"
    if [ -n "${QUERYLOGS_PG_SERVER:-}" ]; then
        echo "TECHNITIUM_QUERYLOGS_PG_CONFIG={\"server\":\"${QUERYLOGS_PG_SERVER}\",\"username\":\"${QUERYLOGS_PG_USERNAME}\",\"password\":\"${QUERYLOGS_PG_PASSWORD}\",\"port\":${QUERYLOGS_PG_PORT},\"databaseName\":\"${QUERYLOGS_PG_DATABASE}\"}"
    fi
    if [ -n "${SSO_AUTHORITY:-}" ]; then
        echo "TECHNITIUM_SSO_CONFIG={\"authority\":\"${SSO_AUTHORITY}\",\"clientId\":\"${SSO_CLIENT_ID}\",\"clientSecret\":\"${SSO_CLIENT_SECRET}\",\"groupMap\":\"${SSO_GROUP_MAP}\"}"
    fi
    if [ -n "${PROXMOX_DNS_SYNC_TECHNITIUM_API:-}" ]; then
        echo "PROXMOX_DNS_SYNC_TECHNITIUM_API=\"${PROXMOX_DNS_SYNC_TECHNITIUM_API}\""
    fi
    if [ -n "${PROXMOX_DNS_SYNC_ZONE:-}" ]; then
        echo "PROXMOX_DNS_SYNC_ZONE=\"${PROXMOX_DNS_SYNC_ZONE}\""
    fi
} > secrets/bw.env
chmod 600 secrets/bw.env

###############################################################################
# technitium/terraform/local/terraform.tfvars (production)
###############################################################################
cat > technitium/terraform/local/terraform.tfvars << EOF
###############################################################################
# Generated by scripts/generate-config.sh from secrets/deployment.env.
# Do not hand-edit -- edit deployment.env and re-run the script instead.
###############################################################################

pm_api_url  = "${PM_API_URL}"
pm_user     = "${PM_USER}"
pm_password = "${PM_PASSWORD}"

pm_node         = "${PM_NODE}"
target_node     = "${TARGET_NODE}"
datastore       = "${DATASTORE}"
ns2_target_node = "${NS2_TARGET_NODE}"

temp_vm_ip     = "${TEMP_VM_IP}"
prod_vm_ip     = "${PROD_VM_IP}"
gateway_ip     = "${GATEWAY_IP}"
ns2_prod_vm_ip = "${NS2_PROD_VM_IP}"
ns2_temp_vm_ip = "${NS2_TEMP_VM_IP}"

cloud_init_image_id = "${CLOUD_INIT_IMAGE_ID}"

vm_password = "${VM_PASSWORD}"
ssh_pubkey  = "${SSH_PUBKEY}"

rebuild_id     = "${REBUILD_ID}"
ns2_rebuild_id = "${NS2_REBUILD_ID}"
EOF
chmod 600 technitium/terraform/local/terraform.tfvars

###############################################################################
# technitium/terraform/local/staging.tfvars
###############################################################################
cat > technitium/terraform/local/staging.tfvars << EOF
###############################################################################
# Generated by scripts/generate-config.sh from secrets/deployment.env.
# Do not hand-edit -- edit deployment.env and re-run the script instead.
###############################################################################

pm_api_url  = "${PM_API_URL}"
pm_user     = "${PM_USER}"
pm_password = "${PM_PASSWORD}"

pm_node         = "${PM_NODE}"
target_node     = "${TARGET_NODE}"
datastore       = "${DATASTORE}"
ns2_target_node = "${NS2_TARGET_NODE}"

prod_vm_ip     = "${STAGING_PROD_VM_IP}"
temp_vm_ip     = "${STAGING_TEMP_VM_IP}"
ns2_prod_vm_ip = "${STAGING_NS2_PROD_VM_IP}"
ns2_temp_vm_ip = "${STAGING_NS2_TEMP_VM_IP}"
gateway_ip     = "${GATEWAY_IP}"

cloud_init_image_id = "${CLOUD_INIT_IMAGE_ID}"

vm_password = "${VM_PASSWORD}"
ssh_pubkey  = "${SSH_PUBKEY}"
$( [ -n "${SSH_PRIVKEY:-}" ] && echo "ssh_privkey = \"${SSH_PRIVKEY}\"" )

dns_hostname = "${STAGING_DNS_HOSTNAME}"
acme_server  = "${STAGING_ACME_SERVER}"
nfs_subdir   = "${STAGING_NFS_SUBDIR}"
is_staging   = true
EOF
chmod 600 technitium/terraform/local/staging.tfvars

###############################################################################
# technitium/cloud-init/local/technitium-user.yaml (ns1)
###############################################################################
cat > technitium/cloud-init/local/technitium-user.yaml << EOF
#cloud-config
# Generated by scripts/generate-config.sh from secrets/deployment.env.
# Do not hand-edit -- edit deployment.env and re-run the script instead.
hostname: ${NS1_HOSTNAME}
fqdn: ${NS1_HOSTNAME}.${BASE_DOMAIN}

ssh_authorized_keys:
  - ${SSH_PUBKEY}

ssh_pwauth: true
disable_root: false

chpasswd:
  expire: false

packages:
  - qemu-guest-agent
  - python3
  - python3-pip
  - git
  - curl
  - wget
  - ca-certificates
  - ansible
  - jq
  - unzip

timezone: ${TIMEZONE}

write_files:
  - path: /opt/infra/.gitkeep
    content: ""

  ###########################################################################
  # Technitium default admin password (required for API bootstrap)
  ###########################################################################
  - path: /etc/technitium/default-admin-password
    content: |
      admin
    permissions: "0600"

runcmd:
  - apt-get update -y || true
  - apt-get upgrade -y || true
  - systemctl enable qemu-guest-agent || true
  - systemctl start qemu-guest-agent || true

  ###########################################################################
  # Clone your GitOps repo
  ###########################################################################
  - git clone https://gitea.example.com/example-org/technitium.git /opt/infra/technitium || true

  ###########################################################################
  # bw.env is delivered by Terraform (file provisioner, over SSH) after this
  # cloud-init run completes, then the Ansible playbooks below are triggered
  # by Terraform's remote-exec provisioner. See technitium/terraform/main.tf.
  ###########################################################################

final_message: "Technitium DNS Server base image initialized via cloud-init."
EOF

###############################################################################
# technitium/cloud-init/local/technitium-user-ns2.yaml
###############################################################################
cat > technitium/cloud-init/local/technitium-user-ns2.yaml << EOF
#cloud-config
# Generated by scripts/generate-config.sh from secrets/deployment.env.
# Do not hand-edit -- edit deployment.env and re-run the script instead.
hostname: ${NS2_HOSTNAME}
fqdn: ${NS2_HOSTNAME}.${BASE_DOMAIN}

ssh_authorized_keys:
  - ${SSH_PUBKEY}

ssh_pwauth: true
disable_root: false

chpasswd:
  expire: false

packages:
  - qemu-guest-agent
  - python3
  - python3-pip
  - git
  - curl
  - wget
  - ca-certificates
  - ansible
  - jq
  - unzip

timezone: ${TIMEZONE}

write_files:
  - path: /opt/infra/.gitkeep
    content: ""

  ###########################################################################
  # Technitium default admin password (required for API bootstrap)
  ###########################################################################
  - path: /etc/technitium/default-admin-password
    content: |
      admin
    permissions: "0600"

runcmd:
  - apt-get update -y || true
  - apt-get upgrade -y || true
  - systemctl enable qemu-guest-agent || true
  - systemctl start qemu-guest-agent || true

  ###########################################################################
  # Clone your GitOps repo
  ###########################################################################
  - git clone https://gitea.example.com/example-org/technitium.git /opt/infra/technitium || true

  ###########################################################################
  # bw.env is delivered by Terraform (file provisioner, over SSH) after this
  # cloud-init run completes, then the Ansible playbooks below are triggered
  # by Terraform's remote-exec provisioner. See technitium/terraform/ns2.tf.
  ###########################################################################

final_message: "Technitium DNS Server (ns2) base image initialized via cloud-init."
EOF

echo "Generated (from ${DEPLOYMENT_ENV}):"
echo "  secrets/bw.env"
echo "  technitium/terraform/local/terraform.tfvars"
echo "  technitium/terraform/local/staging.tfvars"
echo "  technitium/cloud-init/local/technitium-user.yaml"
echo "  technitium/cloud-init/local/technitium-user-ns2.yaml"
